source 'https://cdn.cocoapods.org/'
install! 'cocoapods', :generate_multiple_pod_projects => true
use_frameworks!

target 'Stuart_Example' do
  pod 'Stuart', :path => '../'

  target 'Stuart_Tests' do
    inherit! :search_paths

  end
end
